steps:
- uses: actions/checkout@v2
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.x'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pipenv
    pipenv install --dev # install dev dependencies
- name: Test with pytest
  run: |
    pytest tests.py